#!/bin/bash

echo " Assistant de capture d'écran pour l'application Gestion de Notes"
echo "=================================================="
echo ""
echo "1. Assurez-vous que l'application est en cours d'exécution sur http://localhost:8000"
echo "2. Ajoutez quelques notes d'exemple pour rendre la capture plus intéressante"
echo ""
echo "Sur Mac :"
echo "  - Appuyez sur Cmd + Shift + 4 pour capturer une zone"
echo "  - Sélectionnez la fenêtre du navigateur"
echo "  - Sauvegardez dans : screenshots/interface-principale.png"
echo ""
echo "Sur Windows :"
echo "  - Appuyez sur Windows + Shift + S"
echo "  - Sélectionnez la zone à capturer"
echo "  - Sauvegardez dans : screenshots/interface-principale.png"
echo ""
echo "La capture apparaîtra automatiquement dans le README ✅"